### PR TITLE
#31 added a feature for searching notes

### PR DESCRIPTION
**Pull request by Collid3**
#31 added a feature for searching notes and a p tag when the search is not found

### CODE REVIEW

**Comment by pythonpioneer** [comment]
@Collid3 I'll review it ASAP and will notify you. Thank you for your contribution.

**Comment by Collid3** [comment]
Looking forward to your response

**Comment by Collid3** [comment]
> @Collid3 I'll review it ASAP and will notify you. Thank you for your contribution.

**Comment by pythonpioneer** [comment]
Hey @Collid3 I am working on some other issues. I'll let you know about your contribution.

**Review by pythonpioneer — CHANGES_REQUESTED** [review]
### Change Request

- Please hide the filter, the add, and the logout icons when searching.
- Search is only working on Title and it is case-sensitive.
- Allow it to work with all cases.
- And, also enables search for descriptions. (The results are not reflecting on screen)

##
### Screen Shots
- Case Sensitive
Screenshot 2023-09-21 at 4 22 20 PM
<br>
Screenshot 2023-09-21 at 4 19 35 PM

<br>
<br>
<br>

- Searching in desc
Screenshot 2023-09-21 at 4 19 45 PM

##
### Pull Request

- Please add the work descriptions to your pull request. So, that I can verify it easily.
- And make sure to take pull before changes.
- And when making a pull request, convert your editor `default-spaces: 4`.

> Thank @Collid3 for your contribution.

**Comment by Collid3** [comment]
sorry for those many commits. I made a mistake when pulling the changes from upstream

**Review by pythonpioneer — CHANGES_REQUESTED** [review]
Hey @Collid3 
Please take pull once and make the changes required based on the latest pull.

**Pull request closed without merging**
