### PR TITLE
# 36 added toasts for actions

### LINKED ISSUE #36: Alerts
### Issue

- Add alerts for all possible actions.
- For Logged In.
- For Logged out.
- For Notes Created.
- For Notes Deleted.
- For Notes Updated.
- For Invalid credentials
- For API response

> Inherit the issue after solving one or more requests, If any.

### PR DESCRIPTION
**Pull request by Ehsan-Yari**

### CODE REVIEW

**Comment by pythonpioneer** [comment]
Thank @Ehsan-Yari for the contribution. I'll review it and notify you ASAP.

**Comment by Ehsan-Yari** [comment]
> Thank @Ehsan-Yari for the contribution. I'll review it and notify you ASAP.

You're welcome! I'm glad to hear that I was able to help. If you have any more questions or need further assistance, don't hesitate to ask. I'm here to help.

**Review by pythonpioneer — APPROVED** [review]
all good

**Review by Ehsan-Yari — COMMENTED** [review]
nice

**Pull request merged**
